steps:
- name: docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']
- name: build
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']
- name: run_gke
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1-c
  - --cluster=gcp-devops-project-cluster
  - --namespace=gcp-devops-prod